### ISSUE TITLE
Unable to configure a key as Enter+Layer shift

### ISSUE THREAD

**Issue by jacereda** [keyboardio/Chrysalis#652]
**Describe the bug**
On 0.8.2 I'm unable to configure the Enter key as a layer shift when held. Had to rollback to 0.7.9.

**To Reproduce**
On layer 0, tell the Enter key it should shift to layer 6. Looks like it messes modifiers somehow and modifiers mess the layer shift. 
**Desktop (please complete the following information):**
 - OS: Windows 10
 - Chrysalis Version: 0.8.2

**Comment by tmarzolf** [comment]
I think I'm seeing the same behavior with space as a layer shift when held on 0.8.3 Snapshot

**Comment by Rom1deTroyes** [comment]
Can't reproduce this on Debian GNU/Linux (Chrysalis 0.8.3-snapshot.AppImage).

![Chrysalis-0.8.3-snapshot](https://user-images.githubusercontent.com/8625432/106660007-c688ed80-659f-11eb-8c53-9964ff4b93f9.png)

This problem should be resolved by commit commit 50de8b7e573f413dd0c1add21726893abda85645 (api/keymap: Fix the dualuse database entries). Does your 0.8.3-snapshot older than Thu Jan 28 11:28:52 2021 +0100 ?

**Comment by Rom1deTroyes** [comment]
@jacereda : The Chrysalis-0.8.2 release has some problems with this function that has been corrected in the dev snapshot available here : https://github.com/keyboardio/Chrysalis/releases/tag/v0.8.3-snapshot

**Comment by tmarzolf** [comment]
This works for me on a current 0.8.3 snapshot on Win 10

**Comment by amperecz** [comment]
I had same problem on 0.8.2. for atreus, the 0.8.3 has resolved it. however for model 01, the secondary action still doesn't work on both versions. (on backspace and space).

**Comment by algernon** [comment]
@amperecz Apologies for the late reply, but on the Model01, are you running the experimental firmware, or the default one? The default doesn't support secondary actions at all.

Meanwhile, as the key can be selected in 0.8.3-snapshot, I'm closing this issue. If it's still a problem, please feel free to reopen.
